package:
  name: python-fcl
  version: 0.3.1

source:
#  git_url: https://github.com/jf---/python-fcl
#  git_tag: jf/mesh-support-ccd
  path: ../../


build:
   number: 2
   binary_relocation: true # (defaults to true)

requirements:
  build:
    - python
    - cython
    - numpy
    - flann
    - libccd
    - fcl
  run:
    - python
    - numpy
    - flann
    - libccd
    - fcl

about:
  home: https://github.com/jf---/python-fcl
  license: BSD
  summary: This library is a Python binding of FCL library
