
env:
  global:
    - CIBW_BEFORE_BUILD="yum install -y cmake3 eigen3 &&\
                         ln -s /usr/bin/cmake3 /usr/bin/cmake &&\
                         ls /usr/bin &&\
                         bash requirements/clone.bash &&\
                         bash requirements/build.bash"
    
matrix:
  include:
    - dist: trusty
      sudo: required
      language: python
      python: "3.6"
      services:
        - docker
    - os: osx
      language: python

install:
  # Python 3 is needed to run cibuildwheel 
  - if [ "${TRAVIS_OS_NAME:-}" == "osx" ]; then
      brew install python3;
    fi
# Install cibuildwheel using pip3 to make sure Python 3 is used.
  - pip3 install cibuildwheel==0.6.0

script:
  - cibuildwheel --output-dir wheelhouse
