name: Build

on: [push, pull_request, workflow_dispatch]

jobs:
  formatting:
    name: Check Formatting
    runs-on: ubuntu-latest
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3
      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: ruff
        run: |
          pip install ruff
          ruff .

  build_wheels:
    name: Build wheel on ${{matrix.platform}}
    runs-on: ${{matrix.platform}}
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v3
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.15.0
        env:
          CIBW_ARCHS_MACOS: 'x86_64 arm64'
      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
